---

- hosts: localhost
  connection: local
  become: yes
  become_user: root
  become_method: sudo
  vars:
     core_packages: ['software-properties-common', 'certbot', 'python-certbot-apache', 'ec2-instance-connect', 'apache2']
  tasks:

  - name: Enable universe repository
    apt_repository:
      repo: "{{ item }}"
    loop:
      - "deb http://archive.ubuntu.com/ubuntu/ bionic universe"
      - "deb http://archive.ubuntu.com/ubuntu/ bionic-updates universe"
      - "deb http://security.ubuntu.com/ubuntu/ bionic-security universe"

  - name: add certbot repository
    apt_repository:
      repo: 'ppa:certbot/certbot'
      state: present

  - name: upgrade dist
    apt:
      upgrade: 'yes'

  - name: install core packages
    apt:
      name: "{{ core_packages }}"
      update_cache: yes
      state: present

  - name: clone project0 repo
    git:
      repo: https://github.com/alexcoward/Project0.git
      dest: /tmp/project0

  - name: copy index.html
    copy:
      src: /tmp/project0/html_docs/index.html
      dest: /var/www/html/index.html

  - name: copy image
    copy:
      src: /tmp/project0/html_docs/logo2.png
      dest: /var/www/html/logo2.png

  - name: copy teamaerialcsun.gq default vhost config
    copy:
      src: /tmp/project0/apache_conf/000-default.conf
      dest: /etc/apache2/sites-available/000-default.conf

  - name: generate an OpenSSH keypair with the default values (4096 bits, rsa)
    openssh_keypair:
      path: /tmp/github

  - name: add a new read-only deploy key to a GitHub repository using basic authentication
    github_deploy_key:
      owner: "alexcoward"
      repo: "project0secrets"
      name: "new-deploy-key"
      key: "{{ lookup('file', '/tmp/github.pub') }}"
      read_only: yes
      username: ""
      password: ""
      otp: ""

  - name: pull private repo from git
    git:
      repo: git@github.com:alexcoward/project0secrets.git
      dest: /tmp/project0secrets
      key_file: /tmp/github
      accept_hostkey: true
      ssh_opts: "-o StrictHostKeyChecking=no"

  - name: copy secrets
    copy: src={{ item.src }} dest={{ item.dest }}
    with_items:
      - { src: '/tmp/project0secrets/options-ssl-apache.conf', dest: '/etc/apache2/options-ssl-apache.conf' }
      - { src: '/tmp/project0secrets/privkey.pem', dest: '/etc/apache2/privkey.pem' }
      - { src: '/tmp/project0secrets/fullchain.pem', dest: '/etc/apache2/fullchain.pem' }

  - name: enable apache2_module rewrite
    apache2_module:
      state: present
      name: rewrite

  - name: restart apache2
    service:
      name: apache2
      state: restarted